-- ============================================
-- Türkçe Açıklama:
-- Kategori tablosuna 'allowance' (harçlık) türü ekleme
-- ve kategori tablosunu oluşturma migration'ı
-- ============================================

-- 1. KATEGORİ TABLOSU (eğer yoksa oluştur)
CREATE TABLE IF NOT EXISTS public.but_categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    name text NOT NULL,
    type text NOT NULL CHECK (type IN ('income', 'expense', 'allowance')),
    parent_id bigint REFERENCES public.but_categories(id) ON DELETE CASCADE,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now(),
    
    -- Benzersizlik: Aynı kullanıcı aynı isimde kategori oluşturamaz
    UNIQUE(user_id, name)
);

-- 2. ROW LEVEL SECURITY
ALTER TABLE public.but_categories ENABLE ROW LEVEL SECURITY;

-- Kullanıcılar sadece kendi kategorilerini görebilir
CREATE POLICY "Users can view their own categories"
    ON public.but_categories
    FOR SELECT
    USING (auth.uid() = user_id);

-- Kullanıcılar kendi kategorilerini oluşturabilir
CREATE POLICY "Users can create their own categories"
    ON public.but_categories
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Kullanıcılar kendi kategorilerini güncelleyebilir
CREATE POLICY "Users can update their own categories"
    ON public.but_categories
    FOR UPDATE
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- Kullanıcılar kendi kategorilerini silebilir
CREATE POLICY "Users can delete their own categories"
    ON public.but_categories
    FOR DELETE
    USING (auth.uid() = user_id);

-- 3. İNDEXLER (performans için)
CREATE INDEX IF NOT EXISTS idx_but_categories_user_id ON public.but_categories(user_id);
CREATE INDEX IF NOT EXISTS idx_but_categories_type ON public.but_categories(type);
CREATE INDEX IF NOT EXISTS idx_but_categories_parent_id ON public.but_categories(parent_id);

-- 4. TRIGGER: updated_at otomatik güncelleme
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_but_categories_updated_at 
    BEFORE UPDATE ON public.but_categories 
    FOR EACH ROW 
    EXECUTE FUNCTION public.update_updated_at_column();

-- 5. ÖRNEK KATEGORİLER (isteğe bağlı)
-- Bu kısım sadece ilk kurulumda çalıştırılabilir
-- INSERT INTO public.but_categories (user_id, name, type, parent_id) VALUES
-- (auth.uid(), 'Market', 'expense', NULL),
-- (auth.uid(), 'Ulaşım', 'expense', NULL),
-- (auth.uid(), 'Eşime Harçlık', 'allowance', NULL),
-- (auth.uid(), 'Çocuklara Harçlık', 'allowance', NULL),
-- (auth.uid(), 'Maaş', 'income', NULL),
-- (auth.uid(), 'Freelance', 'income', NULL);

-- 6. KATEGORİLERİ HİYERARŞİK OLARAK GETİREN FONKSİYON
CREATE OR REPLACE FUNCTION public.get_categories_hierarchical()
RETURNS TABLE (
    id bigint,
    user_id uuid,
    name text,
    type text,
    parent_id bigint,
    subcategories jsonb
) AS $$
BEGIN
    RETURN QUERY
    WITH RECURSIVE category_tree AS (
        -- Ana kategoriler (parent_id NULL olanlar)
        SELECT 
            c.id,
            c.user_id,
            c.name,
            c.type,
            c.parent_id,
            '[]'::jsonb as subcategories
        FROM public.but_categories c
        WHERE c.user_id = auth.uid() AND c.parent_id IS NULL
        
        UNION ALL
        
        -- Alt kategoriler
        SELECT 
            c.id,
            c.user_id,
            c.name,
            c.type,
            c.parent_id,
            '[]'::jsonb as subcategories
        FROM public.but_categories c
        INNER JOIN category_tree ct ON c.parent_id = ct.id
        WHERE c.user_id = auth.uid()
    )
    SELECT 
        ct.id,
        ct.user_id,
        ct.name,
        ct.type,
        ct.parent_id,
        (
            SELECT jsonb_agg(
                jsonb_build_object(
                    'id', sub.id,
                    'name', sub.name,
                    'type', sub.type,
                    'parent_id', sub.parent_id
                )
            )
            FROM public.but_categories sub
            WHERE sub.parent_id = ct.id AND sub.user_id = auth.uid()
        ) as subcategories
    FROM category_tree ct
    WHERE ct.parent_id IS NULL
    ORDER BY ct.type, ct.name;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Fonksiyon için RLS politikası
GRANT EXECUTE ON FUNCTION public.get_categories_hierarchical() TO authenticated;
