-- SpendMe Bildirim Merkezi — but_notifications tablosu
-- Türkçe Açıklama:
--   In-app bildirim merkezi için. Uygulama zil ikonundan okunur.
--   Idempotency dedupe_key ile sağlanır: aynı olay için aynı kullanıcıda
--   aynı anahtar tekrar insert edilemez (ör. "budget_overshoot:42:2026-04").
--
-- Çalıştırma: Supabase SQL editor'da tek seferde çalıştır.

CREATE TABLE IF NOT EXISTS public.but_notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    type text NOT NULL CHECK (type IN (
        'version_update',
        'budget_warning',
        'budget_overshoot',
        'credit_statement',
        'credit_payment_due',
        'recurring_applied',
        'installment_upcoming'
    )),
    title text NOT NULL,
    body text NOT NULL,
    -- Aksiyonla bağlantı kurmak için opsiyonel meta veri
    related_id bigint,              -- ilgili kayıt (category_id, account_id, transaction_id ...)
    metadata jsonb,                 -- ek detay (tutar, tarih, kategori adı vb.)
    -- Idempotency anahtarı: aynı kullanıcı için aynı olay tekrar yazılmaz
    dedupe_key text NOT NULL,
    read_at timestamptz,
    created_at timestamptz DEFAULT now() NOT NULL,
    UNIQUE(user_id, dedupe_key)
);

-- Hızlı sorgu için indeks
CREATE INDEX IF NOT EXISTS idx_notifications_user_unread
    ON public.but_notifications(user_id, read_at)
    WHERE read_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_notifications_user_created
    ON public.but_notifications(user_id, created_at DESC);

-- Row Level Security
ALTER TABLE public.but_notifications ENABLE ROW LEVEL SECURITY;

-- Kullanıcı sadece kendi bildirimlerini görür
DROP POLICY IF EXISTS "users_select_own_notifications" ON public.but_notifications;
CREATE POLICY "users_select_own_notifications"
    ON public.but_notifications FOR SELECT
    USING (auth.uid() = user_id);

-- Kullanıcı sadece kendi bildirimini ekleyebilir
DROP POLICY IF EXISTS "users_insert_own_notifications" ON public.but_notifications;
CREATE POLICY "users_insert_own_notifications"
    ON public.but_notifications FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Kullanıcı sadece kendi bildirimini güncelleyebilir (okundu işaretleme)
DROP POLICY IF EXISTS "users_update_own_notifications" ON public.but_notifications;
CREATE POLICY "users_update_own_notifications"
    ON public.but_notifications FOR UPDATE
    USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- Kullanıcı sadece kendi bildirimini silebilir
DROP POLICY IF EXISTS "users_delete_own_notifications" ON public.but_notifications;
CREATE POLICY "users_delete_own_notifications"
    ON public.but_notifications FOR DELETE
    USING (auth.uid() = user_id);
